# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages: 
  - stage: "Build_and_Test"
    jobs:
      - job: build
        pool:
          vmImage: 'windows-latest'
        steps:
        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: -c $(buildConfiguration) -f netcoreapp3.0

      - job: test 
        dependsOn: build
        steps:
        - task: DotNetCoreCLI@2
          inputs:
           command: 'test'

      - job: deploy
        dependsOn: build
        steps:
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Free Trial(7b478fea-d20e-4b7e-b3bc-48a9e811376e)'
            appType: 'webApp'
            WebAppName: 'kyles-iq-demo'
            packageForLinux: '$(System.DefaultWorkingDirectory)/DemoProject/bin/Release/netcoreapp3.0/publish/*.zip'

      - job: ping
        dependsOn: deploy
        pool : server
        steps:
        - task: InvokeRESTAPI@1
          inputs:
            connectionType: 'connectedServiceName'
            serviceConnection: 'ping endpoint'
            method: 'GET'
            headers: 
            urlSuffix: '/ping'
            waitForCompletion: 'false'